- name: Install packages to allow apt to use a repository over HTTPS.
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: Install Python packages for SNI verification of CA certificate.
  become: yes
  apt:
    name:
      - python3-urllib3
      - python3-openssl
      - python3-ndg-httpsclient
      - python3-pyasn1
    state: present

- name: Add Docker's official GPG key.
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Set up the stable repository.
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    state: present

- name: Install the latest version of Docker CE.
  become: yes
  apt:
    name:
      - docker-ce
