# Slightly modified example from https://leimao.github.io/blog/Docker-Container-GUI-Display/

FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get -y install \
    firefox \
    libcanberra-gtk-module \
    libcanberra-gtk3-module
RUN apt-get clean

CMD ["sleep", "300"]
