# https://hub.docker.com/_/consul

- name: Create the Consul container (in development mode).
  docker_container:
    comparisons:
      log_opt: strict
    env:
      CONSUL_BIND_INTERFACE: eth0
    image: consul:latest
    log_driver: journald
    name: dev-consul
    published_ports:
      - "0.0.0.0:8500:8500/tcp"
      - "0.0.0.0:8300-8302:8300-8302/tcp"
      - "0.0.0.0:8301-8302:8301-8302/udp"
      - "0.0.0.0:8600:8600/tcp"
      - "0.0.0.0:8600:8600/udp"
    pull: yes
    restart: no
    restart_policy: always
    state: started
