#!/usr/bin/env python3


import argparse
import sys


NAME = "deb-packaging-demo"
VERSION = "1.0.0"


def _syntax():
    parser = argparse.ArgumentParser(description="Demo of Debian packaging process")
    parser.add_argument(
        "-n", "--name", help="Show the name", action="store_true", required=False
    )
    parser.add_argument(
        "-v", "--version", help="Show the version", action="store_true", required=False
    )
    return parser


def main(name, version):
    if name:
        print(NAME)

    if version:
        print(VERSION)

    if not name and not version:
        print("Demo says hi!")

    return 0


if __name__ == "__main__":
    sys.exit(main(**vars(_syntax().parse_args())))
